### ISSUE TITLE
Contradictions

### ISSUE THREAD

**Issue by MayorUshanka** [krychu/wfc#6]
What are some techniques for avoiding contradictions? I'm trying to do a wfc on nyan cat:
![nyan3](https://user-images.githubusercontent.com/25864212/148462228-869169c1-98db-4bae-b614-246c4930daac.png)

But sooner or later it always seems to exit citing that some contradiction occurred. For example:

```
./wfc -m overlapping -w 256 -h 256 -W 3 -H 3 -x 0 -e 1 -y 0 -r 0 nyan.png output5.png

method:               overlapping
seed:                 1641508864

input image:          nyan.png
input size:           44x33
input components:     4
tile size:            3x3
expand input:         1
xflip tiles:          0
yflip tiles:          0
rotate tiles:         0
tile count:           566

output image:         output5.png
output size:          256x256
cell count:           65536

cells collapsed:      275
Contradiction occurred, try again

```

**Comment by MayorUshanka** [comment]
![output5](https://user-images.githubusercontent.com/25864212/148462359-57dd30bf-5573-412f-af08-e52338b5f53f.png)
Note that for an output size of 64 by 64, it seems to work ok!

**Comment by krychu** [comment]
This is a nice example image :)

*One note upfront: `make` was set to build debug version by default. I pushed a change to build non-debug, optimized code by default which should give a significant speed up.*

Some implementations use backtracking or partitioning to mitigate contradictions. But from what I've read, they don't always seem to give tangible benefits compared to restarting the simulation. I haven't looked into it much though.

One thing you can do is to keep your input image not extremely varied in terms of NxN tiles that are extracted (3x3 by default). Contradictions are less likely when the tiles are more robust, that is, they are flexible in all directions and can match many other tiles. Hope this makes some sense. Take a look at the examples in the readme, the input images are often fairly simple patterns, with few colors, and few details. However, some experimentation is definitely a good idea.

Nyan cat is pretty detailed in that regard, and it results in 2664 tiles if you run `wfc` without any arguments. That's quite a lot. But I too managed to get some results by toning down the number of tiles and output resolution:

48x48 output, 530 tiles: `./wfc -m overlapping -e 0 -x 0 -y 0 -r 0 -w 48 -h 48 ~/Downloads/nyan.png output.png`
![output](https://user-images.githubusercontent.com/947457/148608957-ed9f7e59-ff1a-4ba9-929f-2fb204667ba1.png)

80x80 output, 530 tiles: `./wfc -m overlapping -e 0 -x 0 -y 0 -r 0 -w 80 -h 80 ~/Downloads/nyan.png output2.png`
![output2](https://user-images.githubusercontent.com/947457/148609024-f4c04978-259f-4538-929e-d949272d02a2.png)

64x64 output, 1447 tiles: `./wfc -m overlapping -e 0 -x 1 -y 1 -r 0 -w 64 -h 64 ~/Downloads/nyan.png output3.png`
![output3](https://user-images.githubusercontent.com/947457/148610380-b19899a4-671e-427e-bbe9-dff6d535fdb4.png)

**Comment by MayorUshanka** [comment]
I see what you're getting at about the flexible tiles. The poptart with pink spots should be easy enough, But the head probably contains some fairly restricted tiles (eyes and cheeks), and without rotation, the tail probably as well, due to its unique grey/black/rainbow connections.

So, I made a nyan cat with just the cat, no stars and no rainbow, which seemed not just way faster (fewer tiles!) but also more robust.

I also found that the bigger the output image, the more likely a contradiction (though it may have been flukes):

```
./wfc -m overlapping -e 0 -x 0 -y 0 -r 0 -w 1024 -h 1024 -W 3 -H 3 only_cat.png output8.png

method:               overlapping
seed:                 1641594663

input image:          only_cat.png
input size:           39x24
input components:     4
tile size:            3x3
expand input:         0
xflip tiles:          0
yflip tiles:          0
rotate tiles:         0
tile count:           334

output image:         output8.png
output size:          1024x1024
cell count:           1048576

cells collapsed:      19
Contradiction occurred, try again
```

Adding more tile options, like rotations and flips, made a collision less likely, which makes sense as it "cheats" to make tiles more robust. (though it also takes longer to collapse since there are now more superpositions)

I've officially spent 3 days of my life getting my computer to generate lovecraftian nyan cat horrors. Thank you for this awesome program.

![output7](https://user-images.githubusercontent.com/25864212/148624874-4082da3b-7a35-496b-85df-a698c0f7a1e1.png)
![output11](https://user-images.githubusercontent.com/25864212/148624935-544be046-23e2-440e-8d5f-0e96b5da3932.png)
![output15](https://user-images.githubusercontent.com/25864212/148624943-313bf6b9-4794-4b8f-aff8-d4400c649eaa.png)



Perhaps more performance gains can be made by giving the process a CPU affinity, or maybe even running it on the GPU. On one hand the recursion makes it tough for the GPU, on the other hand the GPU can match tiles across the entire board in one go in a shader.

**Comment by krychu** [comment]
You get it, all good insights! Inspired by your observations I also tried some versions that immediately came to mind:

rainbow only, `./wfc -w 64 -h 64 -m overlapping input.png output.png`:
![nyan_a](https://user-images.githubusercontent.com/947457/148659645-40d708b1-0a22-4443-ab99-4b4869272a5a.png) -> ![nyan_aa](https://user-images.githubusercontent.com/947457/148659672-e80c5ba6-fba1-49c3-9059-5f63a38c5663.png)

square nyan, `./wfc -w 64 -h 64 -m overlapping input.png output.png`:
![nyan_c](https://user-images.githubusercontent.com/947457/148659732-cc2b527d-1dec-441b-bad7-4e4c0217eec5.png) -> ![nyan_cc](https://user-images.githubusercontent.com/947457/148659787-bee02fb8-c9f7-4c3c-9474-ccbf3e342377.png)

no rainbow, `./wfc -m overlapping input.png output.png`:
![nyan_d](https://user-images.githubusercontent.com/947457/148659763-e6d9ae37-64e8-451b-a080-0ded3885e362.png) -> ![nyan_ddd](https://user-images.githubusercontent.com/947457/148659792-fa07ec5e-7b31-446b-aa85-8f50115c445a.png)

head in body, `./wfc -w 64 -h 64 -m overlapping input.png output.png`:
![nyan_e](https://user-images.githubusercontent.com/947457/148660871-63d585df-e439-4885-add9-0f5ed8888f66.png) -> ![nyan_ee](https://user-images.githubusercontent.com/947457/148660892-20861ed5-5634-446e-b80b-def6a75cb894.png)

head only, `./wfc -x 1 -y 0 -r 0 -W 3 -H 6 -w 64 -h 64 -m overlapping input.png output.png`:
![nyan_f](https://user-images.githubusercontent.com/947457/148661150-dce82b9b-6cd7-43bc-8bb9-6b1d311f5c37.png) -> ![nyan_f2](https://user-images.githubusercontent.com/947457/148661169-b04f30cc-d5d3-41d2-a316-01b6ec928401.png)

> I've officially spent 3 days of my life getting my computer to generate lovecraftian nyan cat horrors.

This is great to hear, although I feel guilty for not having non-debug, optimized code enabled earlier. Things would have generated for you probably 4-5x faster.

The problem with parallel processing, in the case of wfc, is that it's not local: processing of one cell affects unpredicted number of other cells. So multiple processes could be trying to update the same cell in incompatible ways. And also, the choice of the next cell to process requires the previous processing to complete. That's not to say it cannot be made parallel but it will require some creative thinking :) Perhaps multiple processes could attack distant parts of the output image, and some constraints as to which cell to pick next could be relaxed.

There is definitely room for optimization though. I have a few ideas which I'll be trying soon.

Thanks for using wfc!

**Comment by krychu** [comment]
Also got this, but took a bit longer to generate:

no legs no tail, `./wfc -w 64 -h 64 -m overlapping input.png output.png`:
![nyan_b](https://user-images.githubusercontent.com/947457/148680160-bb5ea64a-7c41-478a-a89d-734ec23c1448.png) -> ![nyan_bb](https://user-images.githubusercontent.com/947457/148680166-d19f185a-7997-49d2-8571-30e244e8dec1.png)

**Comment by MayorUshanka** [comment]
Interesting stuff. It might pay off to do link time optimizations. `-flto` for most compilers. Since I had to modify the makefile to add `-lm`, I also took the liberty of adding `-Ofast -flto -funroll-loops -march=native`. I see someone else has already pulled to add `-O3`.

**Comment by krychu** [comment]
I merged a few optimizations. I'm getting additional ~2x speed up. I have a few more ideas but they will require more effort.

Feel free to create a PR with the flags you added :)

**Comment by krychu** [comment]
@MayorUshanka quick note. There was a bug in the calculation of entropy that influenced which cell was picked next to be collapsed. This has a notable effect on the output images. Now, correctly, the frequency of tiles in the output image matches their frequency in the input image. It also leads to fewer contradictions. Here's the issue: https://github.com/krychu/wfc/issues/14.

So I've re-run some of the above examples and am getting more interesting results now. You might want to try it yourself :)

![nyan_aa2](https://user-images.githubusercontent.com/947457/150562604-10b2f61e-5d06-46c6-a267-83c8999108b9.png)

![nyan_bb2](https://user-images.githubusercontent.com/947457/150562658-04336479-2fea-4661-a512-9b36a6bc96e1.png)

![nyan_cc2](https://user-images.githubusercontent.com/947457/150562678-10efb973-8c66-4abc-ab21-7bf5db5adc29.png)

![nyan_dd2](https://user-images.githubusercontent.com/947457/150562702-ce0e3ef4-a569-4faf-9069-e68b4a460899.png)

![nyan_ee2](https://user-images.githubusercontent.com/947457/150562722-59b254d9-9122-4886-8c52-42d1f0008767.png)

![nyan_ff2](https://user-images.githubusercontent.com/947457/150562757-d11d7161-f5fc-45b6-91ee-b38dc4c1f9b1.png)

![perf](https://user-images.githubusercontent.com/947457/150563059-87e8c2bd-63c7-423d-a8d9-72c427d7c6f0.png)

![nyan_gg2](https://user-images.githubusercontent.com/947457/150563110-c4ec60cd-4843-40a2-a979-553f649d71c8.png)

I've also merged a number of performance improvements, things generate much faster now.
